### ISSUE TITLE
MapWidget handles VehicleState objects separately

### ISSUE THREAD

**Issue by LukasWikander** [RISE-Dependable-Transport-Systems/sdvp_qtcommon#7]
A lot of ugly dynamic casts arise from this problem. MapWidget should be as stupid/generic as possible.

The tasks of MapWidget are to handle the map and where the different components in it should be drawn, their traces, scales - high level stuff. If it is necessary to handle some specific type of object in a detailed way, it is better to create a MapModule.

Remove all the getVehicle and similar from MapWidget, and only keep the getObject range of methods.

**Comment by marvind** [comment]
#16
